### ISSUE TITLE
Development milestones for next 6 months

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#5]
- [x]  Auth method
- [x] Server exit method
- [ ] App icon on notification panel
- [ ] Get list of running Neutralino apps
- [ ] Splash image or loader
- [ ] introduce CLI or proper development workflow

**Comment by shalithasuranga** [comment]
Closing this since some of tasks are outdated and we will add new checklist asap
